"""Frozen pre-redesign availability subset; full audit resides in GUI inventory."""
# Full before-inventory SHA-256: f5f02ea5869e533a8ae7474c7679e232e899f325ff8b25adf3398c2096d2e078
BEFORE = {'native_parameter_units': {'baseline': '-',
                            'electricity_price_eur_per_mwh': 'EUR_2023/MWh',
                            'electrolyzer_capex_eur_per_kw': 'EUR_2023/kW',
                            'electrolyzer_specific_electricity_kwh_per_kg_h2': 'kWh/kg_H2',
                            'pv_capex_eur_per_kw': 'EUR_2023/kW',
                            'wind_capex_eur_per_kw': 'EUR_2023/kW',
                            'h2_storage_capex_eur_per_kg_h2': 'EUR_2023/kg_H2',
                            'uniform_real_wacc_fraction': 'fraction',
                            'electricity_price_offset_eur_per_mwh': 'EUR_2023/MWh',
                            'real_wacc_shift_fraction': 'fraction',
                            'real_wacc_multiplier': 'factor',
                            'electrolyzer_capex_factor': 'factor',
                            'electrolyzer_specific_electricity_factor': 'factor',
                            'h2_demand_multiplier': 'factor'},
 'studies': {'eu_2024': {'sites': {'hamburg_moorburg': {'numeric_sensitivity_parameters': {'electrolyzer_capex_eur_per_kw': 'EUR_2023/kW',
                                                                                           'electrolyzer_specific_electricity_kwh_per_kg_h2': 'kWh/kg_H2',
                                                                                           'pv_capex_eur_per_kw': 'EUR_2023/kW',
                                                                                           'wind_capex_eur_per_kw': 'EUR_2023/kW',
                                                                                           'h2_storage_capex_eur_per_kg_h2': 'EUR_2023/kg_H2',
                                                                                           'electricity_price_offset_eur_per_mwh': 'EUR_2023/MWh',
                                                                                           'real_wacc_shift_fraction': 'fraction',
                                                                                           'real_wacc_multiplier': 'factor',
                                                                                           'electrolyzer_capex_factor': 'factor',
                                                                                           'electrolyzer_specific_electricity_factor': 'factor',
                                                                                           'h2_demand_multiplier': 'factor'},
                                                        'profiles': {'D0': {}, 'D1': {}, 'D2': {}}},
                                   'huelva_la_rabida': {'numeric_sensitivity_parameters': {'electrolyzer_capex_eur_per_kw': 'EUR_2023/kW',
                                                                                           'electrolyzer_specific_electricity_kwh_per_kg_h2': 'kWh/kg_H2',
                                                                                           'pv_capex_eur_per_kw': 'EUR_2023/kW',
                                                                                           'wind_capex_eur_per_kw': 'EUR_2023/kW',
                                                                                           'h2_storage_capex_eur_per_kg_h2': 'EUR_2023/kg_H2',
                                                                                           'electricity_price_offset_eur_per_mwh': 'EUR_2023/MWh',
                                                                                           'real_wacc_shift_fraction': 'fraction',
                                                                                           'real_wacc_multiplier': 'factor',
                                                                                           'electrolyzer_capex_factor': 'factor',
                                                                                           'electrolyzer_specific_electricity_factor': 'factor',
                                                                                           'h2_demand_multiplier': 'factor'},
                                                        'profiles': {'D0': {},
                                                                     'D1': {},
                                                                     'D2': {}}}}},
             'namibia': {'sites': {'namibia': {'numeric_sensitivity_parameters': {'electricity_price_eur_per_mwh': 'EUR_2023/MWh',
                                                                                  'electrolyzer_capex_eur_per_kw': 'EUR_2023/kW',
                                                                                  'electrolyzer_specific_electricity_kwh_per_kg_h2': 'kWh/kg_H2',
                                                                                  'pv_capex_eur_per_kw': 'EUR_2023/kW',
                                                                                  'wind_capex_eur_per_kw': 'EUR_2023/kW',
                                                                                  'h2_storage_capex_eur_per_kg_h2': 'EUR_2023/kg_H2',
                                                                                  'electricity_price_offset_eur_per_mwh': 'EUR_2023/MWh',
                                                                                  'real_wacc_shift_fraction': 'fraction',
                                                                                  'real_wacc_multiplier': 'factor',
                                                                                  'electrolyzer_capex_factor': 'factor',
                                                                                  'electrolyzer_specific_electricity_factor': 'factor'},
                                               'profiles': {'D0': {}}}}}}}
